// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz6e550u3Nm5UkPXRWYyJeMqOntZWbVFo',
    appId: '1:115860659435:web:efbc5cab92230520b572ae',
    messagingSenderId: '115860659435',
    projectId: 'todo-flutter-bj',
    authDomain: 'todo-flutter-bj.firebaseapp.com',
    storageBucket: 'todo-flutter-bj.appspot.com',
    measurementId: 'G-9EQEVNGP4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs-yLytvB14I2m7yQhCC-5wXoIpqIhb3k',
    appId: '1:115860659435:android:e348548435c674e9b572ae',
    messagingSenderId: '115860659435',
    projectId: 'todo-flutter-bj',
    storageBucket: 'todo-flutter-bj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALZ0hH417hqlG5eJKOatkruREFnY3jO-g',
    appId: '1:115860659435:ios:15d588f88ee1b3a8b572ae',
    messagingSenderId: '115860659435',
    projectId: 'todo-flutter-bj',
    storageBucket: 'todo-flutter-bj.appspot.com',
    iosClientId:
        '115860659435-hldjvus5fc3hhqlr9o2i21qoq5i0oqid.apps.googleusercontent.com',
    iosBundleId: 'com.example.hw15Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALZ0hH417hqlG5eJKOatkruREFnY3jO-g',
    appId: '1:115860659435:ios:7a83df1b436cd6feb572ae',
    messagingSenderId: '115860659435',
    projectId: 'todo-flutter-bj',
    storageBucket: 'todo-flutter-bj.appspot.com',
    iosClientId:
        '115860659435-3mlftuqfpbg8shl7asdkaaeajd5582vj.apps.googleusercontent.com',
    iosBundleId: 'com.example.hw15Firebase.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz6e550u3Nm5UkPXRWYyJeMqOntZWbVFo',
    appId: '1:115860659435:web:8cbf451242d4cee5b572ae',
    messagingSenderId: '115860659435',
    projectId: 'todo-flutter-bj',
    authDomain: 'todo-flutter-bj.firebaseapp.com',
    storageBucket: 'todo-flutter-bj.appspot.com',
    measurementId: 'G-P05PKTDB02',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBz6e550u3Nm5UkPXRWYyJeMqOntZWbVFo',
    appId: '1:115860659435:web:3a10213efc25ae2bb572ae',
    messagingSenderId: '115860659435',
    projectId: 'todo-flutter-bj',
    authDomain: 'todo-flutter-bj.firebaseapp.com',
    storageBucket: 'todo-flutter-bj.appspot.com',
    measurementId: 'G-27CL5LQ2FB',
  );
}
